### ISSUE TITLE
Add Cannons v2.5.6 to DerPavlov/mvn-repo

### ISSUE THREAD

**Issue by martijn-heil** [DerPavlov/Cannons#11]
Could you please put Cannons v2.5.6 in your maven repository too? As the Vault repository url has been changed, the old Vault repository does no  longer work properly. In Cannons v2.5.5 (the latest version in your maven repository) the old Vault repo link is still used, due to this I can't add Cannons as a dependency, it won't resolve the Vault dependency correctly.

**Comment by DerPavlov** [comment]
I pushed a snapshot

**Comment by martijn-heil** [comment]
Thanks! :)
