### ISSUE TITLE
Can't load chorus plant projectiles by clicking on cannon blocks

### ISSUE THREAD

**Issue by dzjkb** [DerPavlov/Cannons#13]
Right clicking blocks with the chorus plant in hand doesn't fire a PlayerInteractEvent, so a cannon doesn't get loaded if you right click it with a chorus plant (right clicking an interactable block such as the buttons works, but still).

**Comment by DerPavlov** [comment]
I fixed the issue. Minecraft didn't provide an item for this event, but I added a check if the player has really no item in his hand.
