### ISSUE TITLE
Custom cannon fires to the side instead of forward

### ISSUE THREAD

**Issue by eirikh1996** [DerPavlov/Cannons#18]
Hello. I designed a custom cannon in the same ways as the included cannons are saved. Yet I experience a problem I do not experience with the example cannons: Instead of firing forwards from the muzzle, it instead fires to the side
![2019-12-01_01 13 34_2](https://user-images.githubusercontent.com/11066794/69907598-d921f880-13d7-11ea-819c-0e2bc9374d89.png)
![2019-12-01_01 13 35](https://user-images.githubusercontent.com/11066794/69907599-d921f880-13d7-11ea-8938-9231f0edbe03.png)
![2019-12-01_01 13 39](https://user-images.githubusercontent.com/11066794/69907600-d921f880-13d7-11ea-8d0b-f338bf771a90.png)

![2019-12-01_01 11 35](https://user-images.githubusercontent.com/11066794/69907583-b394ef00-13d7-11ea-83aa-797bc243b599.png)
![2019-12-01_01 11 55](https://user-images.githubusercontent.com/11066794/69907584-b394ef00-13d7-11ea-9897-319b3fb4c927.png)
![2019-12-01_01 12 10](https://user-images.githubusercontent.com/11066794/69907585-b394ef00-13d7-11ea-93d1-cd3ecb1e228e.png)

This problem occurs DESPITE designing the cannon schematic correctly

**Comment by hoorigan** [comment]
This often happens if the schematic was saved facing the wrong direction. Try loading the example schematics, and make sure your design faces the same direction as the others.

**Comment by DerPavlov** [comment]
You can set the firing direction in the design config of the cannon by editing the defaultHorizontalFacing (east, south, west or north):
`angles:
  #used to adjust in what direction a projectile is fired from a cannon. adjust this if your cannon is firing sideways or at itself
  defaultHorizontalFacing: west`

Just try a different facing until it works. I also messed up the direction for my designs and they are facing differently.
