### ISSUE TITLE
Auto reload

### ISSUE THREAD

**Issue by MRillyt** [DerPavlov/Cannons#38]
After i place the chest next to the cannon and fire it with redstone. The cannon says nothing loaded. The chest is full and auto redstone is on so I don't get what the issue is. Any help would be well appreciated.
[New WinRAR ZIP archive.zip](https://github.com/DerPavlov/Cannons/files/6017524/New.WinRAR.ZIP.archive.zip)
![image](https://user-images.githubusercontent.com/68813888/108622671-47663700-7432-11eb-91c7-b395b2b2e64a.png)

**Comment by DerPavlov** [comment]
Confirmed. Looks like an issue with worldedit and the wall_sign in the schematic

**Comment by jamesol1** [comment]
> Confirmed. Looks like an issue with worldedit and the wall_sign in the schematic
> 
> Edit: Can you try to load the cannon schematic with worldedit and save it again if it looks ok.
> Edit 2: Updating to the latest Worldedit version 7.2.3 and Spigot 1.16.5 fixed the problem

I tried doing this and found that it would only auto load gunpowder, not the projectile too. Is that a bug? I was under the impression i might be able to join up a bunch of cannons using redstone and click one button to load and fire.

**Comment by MRillyt** [comment]
> Confirmed. Looks like an issue with worldedit and the wall_sign in the schematic
> 
> Edit: Can you try to load the cannon schematic with worldedit and save it again if it looks ok.
> Edit 2: Updating to the latest Worldedit version 7.2.3 and Spigot 1.16.5 fixed the problem

that fixed the issue
