### ISSUE TITLE
BUG - Null Pointer Exception spams console when cannonball explodes anywhere in world with MineResetLite.

### ISSUE THREAD

**Issue by wolfebersahd** [DerPavlov/Cannons#42]
Steps to reproduce:
1. Install the Cannons plugin and all it's requirements.
2. Install [MineResetLite](https://www.spigotmc.org/resources/mineresetlite-with-worldedit-v6-v7-tokenenchant-explosive-support.61713/updates)
Latest version here https://polymart.org/resource/mineresetlite.137
3. Fire a cannon in game

Results:
Errors spam in console.

Expected Results:
No errors in console.

Full errors log:
https://paste.helpch.at/icaqinowij.sql

This is most likely related to the entity being set to Null when bukkit/spigot expects it to be NotNull.
This is most likely relates to #24

**Comment by DerPavlov** [comment]
I use the method world.createExplosion to create the explosions for cannons and up to 1.14 there was no way to set an entity, it was always null.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#createExplosion(double,double,double,float)

Worldguard makes a check if the entity is null or something odd like a snowball.
I noticed that 1.16 has an option to specify the entity, but don't get your hopes up.

From my side I cannot do much, best ask the developer MineRestLite to add a null check.

**Comment by wolfebersahd** [comment]
Cannons version 2.5.10 fixes this issue.

Thanks so much.
