### ISSUE TITLE
1.17.1 Fawe schematics not loading!

### ISSUE THREAD

**Issue by TomLewis** [DerPavlov/Cannons#47]
I'm finally moving from 1.12.2, I spent all of yesterday updating all my .yml configs to be the new 1.13+ format for materials/sounds, but there is an issue with the schematics, I have a LOT of cannons, so I just spent the time loading up all my old 1.12.2 cannon designs via fawe, and re-saving them to make sure they are in a newer format, but cannons complains ```Schematic file is missing a 'Blocks' tag`; does file exist: true```.

Fawe now saves files as .schem and not .schematic so I manually changed the file extension on all the newly saved cannon designs.

Is there a way around this so I can get cannons working on 1.17/1.18?

**Comment by DerPavlov** [comment]
Can you load the .schematic with with worldedit and save them again?

**Comment by TomLewis** [comment]
After LOTS of trial and error, I figured it out, Its FAWE on the server, not how I saved the schematics, After I fixed a schematic being empty, removed FAWE from my server and re-named all my files to `.schematic` I got cannons working.
It looks like WE/FAWE going back ages now uses `.schem`.

And when using FAWE on the server, it cannot load any schematics at all for cannons.
Im going to need FAWE, as I have an entire team that will be regenearing large areas of my world to bring it from 1.12.2 to 1.17 & 1.18 shortly after, can you please look into allowing us to use FAWE please.

So glad I figured that out, i've been at this 2 days trying to migrate from 1.12.2 to 1.17/1.18, I'm worried that i'm going to have to re-create them all again for 1.18 too?

**Comment by DerPavlov** [comment]
Can you provide with one of your designs for testing? I did a test with FAWE a few weeks ago and did work.

I not 100% if I understand the issue. It seems to be related to this issue:
https://github.com/maruohon/litematica/issues/1

**Comment by TomLewis** [comment]
Yeah sure, its just a normal schematic, the issue is when you install FAWE on the server, then it throws the error not being able to load schematics in Cannons.

Im testing using PurPur 1.17.1 using the latest https://www.spigotmc.org/resources/fast-async-worldedit.13932/

Here's a custom cannon of mine that works without FAWE on the server, but throws that error when I have FAWE and breaks all cannons.
https://www.dropbox.com/s/b1d9upg1eqm5a00/cannon_Bronze_Long.schematic?dl=0

Looks like this

![2021-12-21_15 46 38](https://user-images.githubusercontent.com/144046/146958574-9698bf80-3701-4f08-a062-ff0761e4040d.png)

**Comment by DerPavlov** [comment]
I did try to load your cannon design with FAWE and it complained. However, loading the design with worldedit worked fine. 
I copied the design and saved it again with worldedit (or FAWE) and was able to load the schematic with FAWE without issues afterwards.
Make sure to overwrite your old design `//schem save cannon -f` or use a dfiferent name.

**Comment by TomLewis** [comment]
For anyone that finds this issue later on, you have to:

- Remove FAWE from your server
- Re-create all cannons using WorldEdit (Not with FAWE)
- Re-add FAWE and the cannon files will load.
